import type { LLMProvider } from "@/components/ai/core/providers";

// ── File types supported for document generation ──
export type DocFileType = "pptx" | "xlsx" | "pdf";

// ── Section content types ──
export type DocSectionType =
  | "title"
  | "text"
  | "table"
  | "chart"
  | "summary"
  | "keyValue"
  | "bulletList"
  | "comparison";

// ── Section definition as generated by orchestration agent ──
export interface AIDocSection {
  id: string;
  name: string;
  type: DocSectionType;
  prompt: string;
  provider: LLMProvider;
  model: string;
}

// ── Section execution result ──
export type DocSectionStatus = "pending" | "running" | "complete" | "error";

export interface AIDocSectionResult {
  sectionId: string;
  status: DocSectionStatus;
  content?: unknown; // structured JSON matching the section type
  error?: string;
  usage?: { inputTokens: number; outputTokens: number };
  latencyMs?: number;
}

// ── Template from orchestration ──
export interface AIDocTemplate {
  id: string;
  name: string;
  description: string;
  fileType: DocFileType;
  sections: AIDocSection[];
  style?: {
    primaryColor?: string;
    fontFamily?: string;
  };
}

// ── Orchestration agent response ──
export interface DocsOrchestrationResult {
  submissionId: string;
  taskTitle: string;
  taskDescription: string;
  templates: AIDocTemplate[];
}

// ── Inline doc config for rendering docs inside chat ──
export interface DocConfig {
  id: string;
  template: AIDocTemplate;
  submissionId: string;
  savedSessionId?: string;
  savedSections?: Record<string, AIDocSectionResult>;
  savedDownloadUrl?: string;
}
