import type { LLMProvider } from "@/components/ai/core/providers";

// ── Output format for column results ──
export type ColumnOutputFormat =
  | "text"
  | "number"
  | "boolean"
  | "json"
  | "markdown"
  | "badge";

// ── Column definition as generated by orchestration agent ──
export interface AITableColumnDef {
  id: string;
  name: string;
  description: string;
  systemPrompt: string;
  provider: LLMProvider;
  model: string;
  tools: string[];
  outputFormat: ColumnOutputFormat;
  temperature?: number;
  maxTokens?: number;
  budgetTokens?: number;
  presetId?: string;
  agentSettings?: Record<string, string>;
  isUserInput?: boolean;
}

// ── Row = a document in the submission ──
export interface AITableRow {
  documentId: string;
  filename: string;
  documentType: string | null;
  extractionStatus: string;
}

// ── Cell execution state ──
export type CellStatus = "pending" | "running" | "complete" | "error";

export interface AITableCell {
  rowId: string;
  columnId: string;
  status: CellStatus;
  result?: string;       // concise 1-2 word answer shown in cell
  detail?: string;       // full explanation (shown in drawer)
  sourceText?: string;   // exact quote from source document (shown in drawer)
  error?: string;
  usage?: { inputTokens: number; outputTokens: number };
  latencyMs?: number;
}

// ── Use case suggestion from orchestration ──
export interface AITableUseCase {
  id: string;
  name: string;
  description: string;
  columns: AITableColumnDef[];
  documentFilter?: {
    documentTypes?: string[];
    documentIds?: string[];
  };
}

// ── Orchestration agent response ──
export interface TablesOrchestrationResult {
  submissionId: string;
  taskTitle: string;
  taskDescription: string;
  inputDocuments: AITableRow[];
  useCases: AITableUseCase[];
}

// ── Full table state ──
export interface AITableState {
  id: string;
  submissionId: string;
  useCase: AITableUseCase;
  rows: AITableRow[];
  columns: AITableColumnDef[];
  cells: Record<string, AITableCell>; // key = `${rowId}:${columnId}`
  isRunning: boolean;
  createdAt: Date;
}

// ── Inline table config (for rendering tables inside chat) ──
export interface TableConfig {
  id: string;
  useCase: AITableUseCase;
  rows: AITableRow[];
  submissionId: string;
  savedSessionId?: string;
  savedColumns?: AITableColumnDef[];
  savedCells?: Record<string, AITableCell>;
}

export function cellKey(rowId: string, columnId: string): string {
  return `${rowId}:${columnId}`;
}
